[variables]
NIXPACKS_PYTHON_VERSION = "3.9"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "python39", "python39Packages.pip"]

[phases.install]
cmds = [
    "npm ci",
    "pip install -r scripts/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"