[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/paraphrase/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"