[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/paraphrase/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"
USE_AI_PARAPHRASE = "false"
USE_ADVANCED_PARAPHRASE = "true"
RATE_LIMIT_TTL = "60"
RATE_LIMIT_MAX = "100"
BULK_RATE_LIMIT_TTL = "60"
BULK_RATE_LIMIT_MAX = "10"