services:
  - type: web
    name: paraphraser-api
    env: node
    plan: starter
services:
  - type: web
    name: paraphraser-api
    env: node
    plan: starter
    buildCommand: |
      # Debug Python environment
      which python3
      python3 --version
      which pip
      pip --version
      # Try different pip install methods
      pip install -r requirements.txt || python3 -m pip install --user -r requirements.txt || python3 -m pip install -r requirements.txt
      # Verify installation
      python3 -c "import transformers; print('Transformers installed successfully')"
      # Install Node.js dependencies and build
      npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /paraphrase/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 10
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
