services:
  - type: web
    name: paraphraser-api
    env: node
    plan: starter
    buildCommand: |
      # Install Python dependencies
      python3 -m pip install --user -r requirements.txt
      # Install Node.js dependencies and build
      npm ci && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /paraphrase/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 10
      - key: PYTHONPATH
        value: /opt/render/project/src
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
